### ISSUE TITLE
Multi-level folders are a pain to use and are not imported correctly from Chrome

### ISSUE THREAD

**Issue by akatrevorjay** [raindropio/extensions#13]
See subject. It's horrible. I paid for pro to get this support, and it's half baked :(

Is the source available for the backend? I'd love to contribute this for free.
I emailed many times and was told they'd get back to me and so far no response after weeks...

**Comment by ChristianBagley** [comment]
I can't comment on the issue you're having with importing from Chrome (I didn't import anything), but I agree that there are quite a few 'nuisance' issues. I know that the developers have been working on other projects, so maybe that's why you're experiencing a long response time? 

Back to the import problem. I know using the Mac app, importing bookmarks simply doesn't work. Clicking the option does nothing, no response.

**Comment by akatrevorjay** [comment]
Agreed. Please open source this project if you're not going to develop it.
